// SETUP: mkdir -p "app/account/membership" && code "app/account/membership/page.tsx"
//
// Everything about the customer's membership.

import { createClient } from "@/lib/supabase/server";
import { SignedOut } from "../page";
import MembershipCard, { type Membership } from "../MembershipCard";

function one<T>(v: T | T[] | null | undefined): T | null {
  if (!v) return null;
  return Array.isArray(v) ? v[0] ?? null : v;
}

const STATUS_TEXT: Record<string, string> = {
  offered: "Matching a provider",
  declined: "Finding someone else",
  scheduled: "Confirmed",
  in_progress: "In progress",
  completed: "Completed",
  cancelled: "Cancelled",
};

export default async function MembershipPage() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return <SignedOut area="client" />;

  const { data: sub } = await supabase
    .from("subscriptions")
    .select(
      "id, status, start_date, contract_length_months, cycles_billed, current_period_end, preferred_weekday, preferred_hour, postcode, paused_until, packages(name, price, visits_per_month, inclusions, good_to_know, duration_minutes)"
    )
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (!sub) {
    return (
      <main style={wrap}>
        <link rel="stylesheet" href={FONTS} />
        <div style={{ maxWidth: 720, margin: "0 auto", paddingTop: 40 }}>
          <p style={eyebrow}>Your account</p>
          <h1 style={h1}>Membership</h1>
            <div style={{ ...card, textAlign: "center", padding: "40px 26px" }}>
            <h2 style={{ ...sectionTitle, margin: "0 0 8px" }}>
              You don&apos;t have a membership
            </h2>
            <p style={{ color: "#6e7a70", margin: "0 0 20px" }}>
              A membership schedules your visits automatically and keeps the same
              trusted team. Or keep booking one visit at a time — entirely up to
              you.
            </p>
            <a href="/subscribe" style={btn}>
              See memberships
            </a>
            <p style={{ marginTop: 16 }}>
              <a href="/book" style={link}>
                or book a single visit →
              </a>
            </p>
          </div>
        </div>
      </main>
    );
  }

  const pkg = one(sub.packages as never) as {
    name: string;
    price: number;
    visits_per_month: number | null;
    inclusions: string[] | null;
    good_to_know: string[] | null;
    duration_minutes: number | null;
  } | null;

  // Visits generated by this subscription
  const { data: visits } = await supabase
    .from("bookings")
    .select("id, scheduled_at, status, packages(name)")
    .eq("subscription_id", sub.id)
    .order("scheduled_at", { ascending: false });

  const all = visits ?? [];
  const upcoming = all.filter((v) =>
    ["offered", "declined", "scheduled", "in_progress"].includes(v.status)
  );

  // Billing history
  const { data: pays } = await supabase
    .from("payments")
    .select("id, gross_amount, created_at, status")
    .eq("subscription_id", sub.id)
    .order("created_at", { ascending: false });

  const membership: Membership = {
    id: sub.id,
    planName: pkg?.name ?? "Membership",
    price: Number(pkg?.price ?? 0),
    status: sub.paused_until ? "paused" : sub.status,
    startDate: sub.start_date,
    contractMonths: sub.contract_length_months ?? 3,
    cyclesBilled: sub.cycles_billed ?? 0,
    nextBill: sub.current_period_end,
    weekday: sub.preferred_weekday,
    hour: sub.preferred_hour,
    postcode: sub.postcode,
    visitsThisCycle: upcoming.length,
    visitsPerMonth: pkg?.visits_per_month ?? null,
    pausedUntil: sub.paused_until,
  };

  const when = (iso: string) =>
    new Date(iso).toLocaleString("en-GB", {
      weekday: "short",
      day: "numeric",
      month: "short",
      hour: "2-digit",
      minute: "2-digit",
      hour12: true,
    });

  const day = (iso: string) =>
    new Date(iso).toLocaleDateString("en-GB", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });

  return (
    <main style={wrap}>
      <link rel="stylesheet" href={FONTS} />
      <div style={{ maxWidth: 720, margin: "0 auto", paddingTop: 40 }}>
        <p style={eyebrow}>Your account</p>
        <h1 style={h1}>Membership</h1>
        <p style={{ color: "#6e7a70", margin: "0 0 26px" }}>{user.email}</p>

        <MembershipCard m={membership} />

        {/* What's included */}
        {pkg?.inclusions && pkg.inclusions.length > 0 && (
          <section style={{ ...card, marginBottom: 20 }}>
            <h2 style={sectionTitle}>What your plan includes</h2>
            <ul style={list}>
              {pkg.inclusions.map((x) => (
                <li key={x} style={li}>
                  {x}
                </li>
              ))}
            </ul>
            {pkg.good_to_know && pkg.good_to_know.length > 0 && (
              <>
                <p style={subHead}>Good to know</p>
                <ul style={list}>
                  {pkg.good_to_know.map((x) => (
                    <li key={x} style={{ ...li, color: "#6e7a70", fontSize: 13.5 }}>
                      {x}
                    </li>
                  ))}
                </ul>
              </>
            )}
          </section>
        )}

        {/* Upcoming visits */}
        <section style={{ ...card, marginBottom: 20 }}>
          <h2 style={sectionTitle}>
            Your visits{upcoming.length ? ` (${upcoming.length} upcoming)` : ""}
          </h2>
          {all.length === 0 ? (
            <p style={{ color: "#6e7a70", margin: 0 }}>
              Your next visits will be scheduled at your next payment.
            </p>
          ) : (
            all.slice(0, 10).map((v) => {
              const p = one(v.packages as never) as { name: string } | null;
              return (
                <div key={v.id} style={row}>
                  <div>
                    <strong style={{ fontSize: 14.5, color: "#2f4a3a" }}>
                      {p?.name ?? "Visit"}
                    </strong>
                    <div style={{ color: "#6e7a70", fontSize: 13 }}>
                      {when(v.scheduled_at)}
                    </div>
                  </div>
                  <span style={{ color: "#6e7a70", fontSize: 13 }}>
                    {STATUS_TEXT[v.status] ?? v.status}
                  </span>
                </div>
              );
            })
          )}
        </section>

        {/* Billing history */}
        <section style={{ ...card, marginBottom: 20 }}>
          <h2 style={sectionTitle}>Payments</h2>
          {(pays ?? []).length === 0 ? (
            <p style={{ color: "#6e7a70", margin: 0 }}>Nothing yet.</p>
          ) : (
            (pays ?? []).map((p) => (
              <div key={p.id} style={row}>
                <div>
                  <strong style={{ fontSize: 14.5 }}>
                    £{Number(p.gross_amount).toFixed(2)}
                  </strong>
                  <div style={{ color: "#6e7a70", fontSize: 13 }}>
                    {day(p.created_at)}
                  </div>
                </div>
                <span
                  style={{
                    fontSize: 12,
                    fontWeight: 600,
                    padding: "5px 12px",
                    borderRadius: 999,
                    background: p.status === "succeeded" ? "#e7eee7" : "#f6e7dd",
                    color: p.status === "succeeded" ? "#2f4a3a" : "#8a4b26",
                  }}
                >
                  {p.status === "succeeded" ? "Paid" : p.status}
                </span>
              </div>
            ))
          )}
        </section>

        {/* Changing things */}
        <section style={card}>
          <h2 style={sectionTitle}>Changing your membership</h2>
          <p style={{ color: "#4a544c", fontSize: 15, lineHeight: 1.6, margin: "0 0 10px" }}>
            You can reschedule or cancel an individual visit from{" "}
            <a href="/account" style={link}>
              My bookings
            </a>{" "}
            — any time before the visit starts. A new appointment time still
            needs the minimum notice shown in the booking picker.
          </p>
          <p style={{ color: "#4a544c", fontSize: 15, lineHeight: 1.6, margin: 0 }}>
            To pause your membership or cancel after your{" "}
            {membership.contractMonths}-month minimum term, contact the Opulence
            Bliss team and we&apos;ll sort it.
          </p>
        </section>
      </div>
    </main>
  );
}

const FONTS =
  "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500&family=Hanken+Grotesk:wght@400;500;600&display=swap";
const wrap: React.CSSProperties = {
  color: "#26302a",
  fontFamily: "'Hanken Grotesk', system-ui, sans-serif",
  padding: 0,
};
const card: React.CSSProperties = {
  background: "#fff",
  border: "1px solid #ece5d8",
  borderRadius: 16,
  padding: "22px 24px",
};
const row: React.CSSProperties = {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  gap: 12,
  padding: "13px 0",
  borderBottom: "1px solid #f0ebe0",
};
const list: React.CSSProperties = {
  listStyle: "none",
  padding: 0,
  margin: 0,
  display: "grid",
  gap: 8,
};
const li: React.CSSProperties = {
  fontSize: 14.5,
  paddingLeft: 18,
  position: "relative",
};
const subHead: React.CSSProperties = {
  fontSize: 11.5,
  fontWeight: 600,
  letterSpacing: "0.1em",
  textTransform: "uppercase",
  color: "#cf854f",
  margin: "18px 0 8px",
};
const eyebrow: React.CSSProperties = {
  textTransform: "uppercase",
  letterSpacing: "0.14em",
  fontSize: 12,
  fontWeight: 600,
  color: "#cf854f",
  margin: "0 0 6px",
};
const h1: React.CSSProperties = {
  fontFamily: "'Fraunces', serif",
  fontWeight: 500,
  fontSize: 38,
  color: "#2f4a3a",
  margin: "0 0 6px",
};
const sectionTitle: React.CSSProperties = {
  fontFamily: "'Fraunces', serif",
  fontWeight: 500,
  fontSize: 20,
  color: "#2f4a3a",
  margin: "0 0 14px",
};
const btn: React.CSSProperties = {
  display: "inline-block",
  background: "#2f4a3a",
  color: "#fbf7f0",
  padding: "12px 26px",
  borderRadius: 999,
  textDecoration: "none",
  fontWeight: 600,
};
const link: React.CSSProperties = { color: "#5b7a65", fontWeight: 600 };
